### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by iarief** [niltonheck/language-freemarker#6]
hi, lately i've always got this error message, could you probably modify the package so that it comply to atom's (possibly new) api?
regards

Store package settings files in the `settings/` directory instead of `scoped-properties/`

```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app/src/package.js:547:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/package.js:168:43)
```

**Comment by iarief** [comment]
nevermind, i've noticed the pull request merge and might only need for it to be available as an update on atom package manager maybe?

**Comment by caffeineshock** [comment]
I'm still getting this error, even though it has been fixed in the repository in april. Is there any chance, we can get a new release?

**Comment by niltonheck** [comment]
Hi @caffeineshock i've not been working with freemarker for quite a while now. I'll try to have a look into this asap.
